# Generated by Django 5.0.2 on 2025-05-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
