# Generated by Django 5.2.1 on 2025-05-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
